more testing

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -53,10 +53,10 @@ jobs:
         npm install || { echo "npm install failed"; exit 1; }
 
         echo "Changing directory to dist..."
-        cd dist || { echo "Directory not found"; exit 1; }
+        cd ./dist || { echo "Directory not found"; exit 1; }
 
         echo "Restarting PM2 process..."
-        pm2 restart index.js || { echo "PM2 restart failed"; exit 1; }
+        pm2 restart 0 || { echo "PM2 restart failed"; exit 1; }
         EOF
 
         echo "Cleaning up SSH key file..."
